"""empty message

Revision ID: 17651c1de5df
Revises: 8ddd091c8f23
Create Date: 2020-06-26 13:32:51.095702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17651c1de5df'
down_revision = '8ddd091c8f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'revenue_type',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'revenue_type',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
