"""empty message

Revision ID: 22720a533ef6
Revises: 46d3693e105f
Create Date: 2020-07-27 14:10:29.716955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22720a533ef6'
down_revision = '46d3693e105f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('break_even', sa.Column('score_unit', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('break_even', 'score_unit')
    # ### end Alembic commands ###
