"""empty message

Revision ID: 366c5057028b
Revises: 79bd10405a4f
Create Date: 2020-08-25 11:02:00.684541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '366c5057028b'
down_revision = '79bd10405a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benchmark', sa.Column('approved_on', sa.DateTime(), nullable=True))
    op.alter_column('benchmark', 'approved',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benchmark', 'approved',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('benchmark', 'approved_on')
    # ### end Alembic commands ###
