"""empty message

Revision ID: 46d3693e105f
Revises: 662c84abe8bb
Create Date: 2020-07-21 12:41:50.308423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46d3693e105f'
down_revision = '662c84abe8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('break_even', sa.Column('applicable', sa.Boolean(), nullable=True))
    op.drop_column('break_even', 'order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('break_even', sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('break_even', 'applicable')
    # ### end Alembic commands ###
