"""empty message

Revision ID: 5e8a3ca5bf14
Revises: 
Create Date: 2020-06-22 10:24:52.396205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8a3ca5bf14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('intro_complete', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry_type', sa.String(length=120), nullable=True),
    sa.Column('business_model', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('month_start', sa.String(length=12), nullable=True),
    sa.Column('month_end', sa.String(length=12), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('total_expenses', sa.Float(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('revenue_type', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('percent_complete', sa.Integer(), nullable=True),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmark.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first', sa.String(length=120), nullable=True),
    sa.Column('last', sa.String(length=120), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmark.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first'),
    sa.UniqueConstraint('last'),
    sa.UniqueConstraint('password')
    )
    op.create_table('impact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('property_code', sa.String(length=80), nullable=False),
    sa.Column('pp_action', sa.String(length=80), nullable=False),
    sa.Column('option_code', sa.String(length=80), nullable=False),
    sa.Column('option_text', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_facet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_property',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('percent_complete', sa.Integer(), nullable=True),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmark.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('impact_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('data', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['impact_id'], ['impact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact_sdg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sdg', sa.String(length=80), nullable=False),
    sa.Column('impact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['impact_id'], ['impact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_property_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('product_property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_property_id'], ['product_property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_property_answer')
    op.drop_table('impact_sdg')
    op.drop_table('impact_answer')
    op.drop_table('survey_data')
    op.drop_table('product_property')
    op.drop_table('product_facet')
    op.drop_table('impact')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('benchmark')
    op.drop_table('company')
    # ### end Alembic commands ###
