"""empty message

Revision ID: 60759d955d02
Revises: f5a6303f415b
Create Date: 2020-09-16 18:22:53.633984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60759d955d02'
down_revision = '14757a74d095'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('company', sa.Column('logo', sa.BLOB(), nullable=True))
    op.add_column('company', sa.Column('logo_file_extension', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'logo')
    op.drop_column('company', 'logo_file_extension')
    # ### end Alembic commands ###
