"""empty message

Revision ID: 662c84abe8bb
Revises: d3b8803dd794
Create Date: 2020-07-20 16:04:12.833132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662c84abe8bb'
down_revision = 'd3b8803dd794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('break_even', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('break_even', 'order')
    # ### end Alembic commands ###
