"""empty message

Revision ID: 7434cfa5ca8d
Revises: add9af66b5d1
Create Date: 2020-08-26 12:51:12.597657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7434cfa5ca8d'
down_revision = 'add9af66b5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benchmark', 'approved_on',
               existing_type=mysql.DATETIME(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benchmark', 'approved_on',
               existing_type=sa.Float(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
