"""empty message

Revision ID: 82879dca121b
Revises: 17651c1de5df
Create Date: 2020-07-15 14:38:58.476756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82879dca121b'
down_revision = '17651c1de5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('break_even',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('benchmark_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmark.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('break_even_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('break_even_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('data', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['break_even_id'], ['break_even.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('break_even_answer')
    op.drop_table('break_even')
    # ### end Alembic commands ###
