"""empty message

Revision ID: 8287d29dec3f
Revises: b4c7479c1534
Create Date: 2020-08-05 11:19:39.749250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8287d29dec3f'
down_revision = 'b4c7479c1534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('break_even', 'score_unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('break_even', sa.Column('score_unit', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
