"""empty message

Revision ID: 8ddd091c8f23
Revises: 7703bc537ac2
Create Date: 2020-06-26 13:15:59.555047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ddd091c8f23'
down_revision = '7703bc537ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'stage',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'stage',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
