"""empty message

Revision ID: 93c8e887bb94
Revises: 7434cfa5ca8d
Create Date: 2020-08-26 13:00:55.968292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93c8e887bb94'
down_revision = '7434cfa5ca8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benchmark', 'approved_on',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=53),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benchmark', 'approved_on',
               existing_type=sa.String(length=53),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
