"""empty message

Revision ID: 94e290609ca6
Revises: 3db93edfb25e
Create Date: 2020-10-02 16:11:34.940601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94e290609ca6'
down_revision = '3db93edfb25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benchmark', 'approved_on',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True)
    op.alter_column('impact_answer', 'data',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('impact_answer', 'data',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('benchmark', 'approved_on',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    # ### end Alembic commands ###
