"""empty message

Revision ID: a034bc630875
Revises: 8287d29dec3f
Create Date: 2020-08-05 12:22:03.933699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a034bc630875'
down_revision = '8287d29dec3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('break_even', sa.Column('awareness_score', sa.Float(), nullable=True))
    op.add_column('break_even', sa.Column('progress_score', sa.Float(), nullable=True))
    op.drop_column('break_even', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('break_even', sa.Column('score', mysql.FLOAT(), nullable=True))
    op.drop_column('break_even', 'progress_score')
    op.drop_column('break_even', 'awareness_score')
    # ### end Alembic commands ###
