"""empty message

Revision ID: add9af66b5d1
Revises: 366c5057028b
Create Date: 2020-08-25 14:08:48.253874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add9af66b5d1'
down_revision = '366c5057028b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('investor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'investor')
    # ### end Alembic commands ###
