"""empty message

Revision ID: b4c7479c1534
Revises: 22720a533ef6
Create Date: 2020-08-03 11:02:56.992381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c7479c1534'
down_revision = '22720a533ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('welcome', sa.Boolean(), nullable=True))
    op.drop_index('first', table_name='user')
    op.drop_index('last', table_name='user')
    op.drop_index('password', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'user', ['password'], unique=True)
    op.create_index('last', 'user', ['last'], unique=True)
    op.create_index('first', 'user', ['first'], unique=True)
    op.drop_column('user', 'welcome')
    # ### end Alembic commands ###
