"""empty message

Revision ID: ba866013e208
Revises: d039f518f020
Create Date: 2020-08-24 13:01:24.095328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba866013e208'
down_revision = 'd039f518f020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('ignored', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'ignored')
    # ### end Alembic commands ###
