"""empty message

Revision ID: d039f518f020
Revises: a034bc630875
Create Date: 2020-08-24 12:22:34.031436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd039f518f020'
down_revision = 'a034bc630875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benchmark', sa.Column('approved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benchmark', 'approved')
    # ### end Alembic commands ###
