"""empty message

Revision ID: d3b8803dd794
Revises: 82879dca121b
Create Date: 2020-07-15 14:49:24.396546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3b8803dd794'
down_revision = '82879dca121b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('break_even_answer', sa.Column('code', sa.String(length=20), nullable=False))
    op.drop_column('break_even_answer', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('break_even_answer', sa.Column('number', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('break_even_answer', 'code')
    # ### end Alembic commands ###
