"""empty message

Revision ID: ec853f1600fd
Revises: 93c8e887bb94
Create Date: 2020-08-26 13:01:07.954055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec853f1600fd'
down_revision = '93c8e887bb94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benchmark', 'approved_on',
               existing_type=mysql.VARCHAR(length=53),
               type_=sa.Float(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benchmark', 'approved_on',
               existing_type=sa.Float(precision=53),
               type_=mysql.VARCHAR(length=53),
               existing_nullable=True)
    # ### end Alembic commands ###
