"""empty message

Revision ID: ff5d561c6c01
Revises: 5e8a3ca5bf14
Create Date: 2020-06-23 14:44:34.544218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff5d561c6c01'
down_revision = '5e8a3ca5bf14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('data', mysql.TEXT(), nullable=True),
    sa.Column('percent_complete', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('benchmark_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmark.id'], name='survey_data_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='survey_data_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
